services:
  server:
    hostname: server
    build: ./server/backend/Hackon
    ports:
      - "8080:8080"
    depends_on:
      - postgres-develop

  postgres-develop:
    image: postgres:17.2-alpine3.20
    container_name: postgres-dev
    environment:
      POSTGRES_HOST: ${DB_HOST_DEV:-localhost}
      POSTGRES_PORT: ${DB_PORT_DEV:-5432}
      POSTGRES_USER: ${DB_USER_DEV:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV:-postgres}
      POSTGRES_DB: ${DB_NAME_DEV:-hackon_dev}
    ports:
      - "${DB_PORT_DEV:-5432}:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  postgres-prod:
    image: postgres:17.2-alpine3.20
    container_name: postgres-prod
    environment:
      POSTGRES_HOST: ${DB_HOST:-localhost}
      POSTGRES_PORT: ${DB_PORT:-5432}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-hackon_prod}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

volumes:
  postgres-dev-data:
  postgres-prod-data:
