spring:
  application:
    name: Hackon

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:hackOn}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: ${DB_HIBERNATE_DDL_AUTO:update}

  # Utilizar apenar no Debug
  # Essa configuraçao impede a criação do bean de EventRepository
  # autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # Desativa a config automatica e retira a necessidade de um DB pre configurado

  # Utilize este configuração apenas para DEBUG em desenvolvimento
  security:
    csrf:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
    # Usuario e senha temporarios
    user:
      name: admin
      password: 1234
    default-target-url: /home