spring:
  application:
    name: Hackon

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: ${DB_HIBERNATE_DDL_AUTO:update}

  # Utilizar apenar no Debug
  # Essa configuraçao impede a criação do bean de EventRepository
  # autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # Desativa a config automatica e retira a necessidade de um DB pre configurado

  # Utilize este configuração apenas para DEBUG em desenvolvimento
  security:
    csrf:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOACK_ISSUERURI}/realms/hackOn
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
    # Usuario e senha temporarios
    user:
      name: admin
      password: 1234
    default-target-url: /home

keycloak:
  server-url: ${KEYCLOACK_URL}
  realm: ${KEYCLOACK_REALM}
  client-id: ${KEYCLOACK_CLIENTID}
  username: ${KEYCLOACK_USER}
  password: ${KEYCLOACK_PASSWORD}
