spring:
  application:
    name: Hackon

  datasource:
    url: jdbc:postgresql://localhost:5432/hackondb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: ${DB_HIBERNATE_DDL_AUTO:update}

  # Utilizar apenar no Debug
  # Essa configuraçao impede a criação do bean de EventRepository
  # autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # Desativa a config automatica e retira a necessidade de um DB pre configurado

  # Utilize este configuração apenas para DEBUG em desenvolvimento
  security:
    csrf:
      enabled: false
    # Usuario e senha temporarios
    user:
      name: admin
      password: 1234
    default-target-url: /home
